### PR TITLE
fix(networks): add more production networks

### LINKED ISSUE #201: Production networks to support
For each we need all the applicable fields in https://github.com/relayprotocol/relay-protocol/blob/main/packages/types/src/types/networks.ts

* Abstract
* Ancient8
* Arbitrum Nova
* B3
* Cyber
* Degen
* Echos
* Game7
* Lisk
* Mint
* Redstone
* Soneium
* Zero

Public RPC endpoints to be found on https://chainlist.org/

### PR DESCRIPTION
**Pull request by clemsos**
I couldnt find Hyperlane address for "Game 7" network : https://docs.hyperlane.xyz/docs/reference/contract-addresses

- fix #201

### CODE REVIEW

File: packages/networks/src/networks/ancient8.ts [hunk 1]
```diff
@@ -0,0 +1,21 @@
...
+  name: 'Ancient8',
+  slug: 'ancient8',
+  hyperlaneMailbox: '0x2f2aFaE1139Ce54feFC03593FeE8AB2aDF4a85A7',
+  bridges: {
+    op: {
+      messagePasser: '0x4200000000000000000000000000000000000016',
+    },
+  },
+  assets: {
+    usdc: '', // TODO: Add USDC address
```
Comment (julien51) [inline packages/networks/src/networks/ancient8.ts:17]: Should we add that?

File: packages/networks/src/networks/arbitrum-nova.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+  l1ChainId: 1,
+  chainId: 42170,
+  isTestnet: false,
+  name: 'Arbitrum Nova',
+  slug: 'arb-nova',
+  hyperlaneMailbox: '0x3a867fCfFeC2B790970eeBDC9023E75B0a172aa7',
+  bridges: {
+    arb: {
+      arbSys: '0x0000000000000000000000000000000000000064',
+      routerGateway: '', // TODO: Add router gateway address
```
Comment (julien51) [inline packages/networks/src/networks/arbitrum-nova.ts:14]: same?

File: packages/networks/src/networks/game7.ts [hunk 3]
```diff
@@ -0,0 +1,27 @@
...
+// https://docs.game7.io/the-g7-network
+
+export const game7: L2NetworkConfig = {
+  stack: 'arb',
+  l1ChainId: 1,
+  chainId: 2187,
+  isTestnet: false,
+  name: 'Game7',
+  slug: 'game7',
+  hyperlaneMailbox: '', // currently not in https://github.com/hyperlane-xyz/hyperlane-registry
```
Comment (clemsos) [inline packages/networks/src/networks/game7.ts:13]: seems like hyperlane does not support that one
